environment:
  DOCKER_USER_NAME: ENCRYPTED[!b1a406d4e2e9ac8261fc78015235cfa9ca2a6e0a6f3ac25fabc4023ec6d3d496c7d46036284167dcfe23cd15f9d6c91a!]
  DOCKER_PASSWORD: ENCRYPTED[!4f8bcd75d1d40bffeac0f70afbc28442e539188311c006ad7bc83215f76064d6788753cf0b54f1dce1ac1aaf75d1b89b!]

docker_builder:
  name: flutter:$DOCKER_TAG
  env:
    # from https://flutter.dev/docs/development/tools/sdk/releases
    matrix:
    - DOCKER_TAG: latest
      FLUTTER_VERSION: 3.7.1
    - DOCKER_TAG: stable
      FLUTTER_VERSION: 3.7.1
    - DOCKER_TAG: beta
      FLUTTER_VERSION: 3.7.0-1.5-pre
  build_script: ./build_docker.sh
  push_script: ./push_docker.sh
